export enum ValidationErrors {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  PASSWORD_DOES_NOT_MATCH = 'PASSWORD_DOES_NOT_MATCH',
  REFRESH_TOKEN_NOT_PROVIDED_IN_COOKIES = 'REFRESH_TOKEN_NOT_PROVIDED_IN_COOKIES',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED',
  REFRESH_TOKEN_REUSE = 'REFRESH_TOKEN_REUSE',
  REFRESH_TOKEN_ERROR = 'REFRESH_TOKEN_ERROR',
}
export enum UnauthorizedLoginError {
  INCORRECT_USER_IDENTIFIER_OR_PASSWORD = 'INCORRECT_USER_IDENTIFIER_OR_PASSWORD',
  LOGIN_DISABLED = 'LOGIN_DISABLED',
  USER_BLOCKED = 'USER_BLOCKED',
  UNREGIESTERED_DEVICE = 'UNREGIESTERED_DEVICE',
  SOMETHING_WENT_WRONG = 'SOMETHING_WENT_WRONG',
}
