version: '3.8'
volumes:
  mysql_data:
    driver: local
services:
  api:
    container_name: spotify-clone
    build: ./
    volumes:
      - .:/apps/spotify-clone
      - /apps/spotify-clone/node_modules
    env_file:
      - .env
    command: npm run start:dev
    depends_on:
      - db
    ports:
      - 8000:8000
    networks:
      - spotifynet
  db:
    container_name: spotify-db
    image: mysql:8.0.33
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spotify
      MYSQL_USER: spotify
      MYSQL_PASSWORD: spotify
    # volumes:
    #   - mysql_data:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - spotifynet
networks:
  spotifynet: {}
